a=open("student.txt","w")
print("Enter the student name:")
name=input()
print("Enter the student enrollment number:")
eno=int(input())
print("Enter the department:"))
dept=input()
a.write("Namw:"+name)
a.write("\nEnrollment number:"+str(eno))
a.write("\nDepartment:"+dept)
a.close()
a=open("student.txt","r")
print(a.read())
