a=open("student.txt","w")
name=input("Enter the name")
eno=input("Enter the enrollment number")
dept=input("Enter the dept")
a.write("Name:"+name)
a.write("\nEnNo:"+str(eno))
a.write("\nDept:"+dept)
a.close()
a=open("student.txt","r")
print(a.read())
